// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetOrderingAgentViewHandlerFunc turns a function with the right signature into a get ordering agent view handler
type GetOrderingAgentViewHandlerFunc func(GetOrderingAgentViewParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOrderingAgentViewHandlerFunc) Handle(params GetOrderingAgentViewParams) middleware.Responder {
	return fn(params)
}

// GetOrderingAgentViewHandler interface for that can handle valid get ordering agent view params
type GetOrderingAgentViewHandler interface {
	Handle(GetOrderingAgentViewParams) middleware.Responder
}

// NewGetOrderingAgentView creates a new http.Handler for the get ordering agent view operation
func NewGetOrderingAgentView(ctx *middleware.Context, handler GetOrderingAgentViewHandler) *GetOrderingAgentView {
	return &GetOrderingAgentView{Context: ctx, Handler: handler}
}

/*
	GetOrderingAgentView swagger:route GET /ordering-agents/{id} getOrderingAgentView

# Get Ordering Agent View

Retrieve the view of an ordering agent.
*/
type GetOrderingAgentView struct {
	Context *middleware.Context
	Handler GetOrderingAgentViewHandler
}

func (o *GetOrderingAgentView) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetOrderingAgentViewParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
