// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"emulation/models"
)

// GetProducingAgentsIDOKCode is the HTTP code returned for type GetProducingAgentsIDOK
const GetProducingAgentsIDOKCode int = 200

/*
GetProducingAgentsIDOK Successful response

swagger:response getProducingAgentsIdOK
*/
type GetProducingAgentsIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ProducingAgentView `json:"body,omitempty"`
}

// NewGetProducingAgentsIDOK creates GetProducingAgentsIDOK with default headers values
func NewGetProducingAgentsIDOK() *GetProducingAgentsIDOK {

	return &GetProducingAgentsIDOK{}
}

// WithPayload adds the payload to the get producing agents Id o k response
func (o *GetProducingAgentsIDOK) WithPayload(payload *models.ProducingAgentView) *GetProducingAgentsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get producing agents Id o k response
func (o *GetProducingAgentsIDOK) SetPayload(payload *models.ProducingAgentView) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProducingAgentsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
