// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetOrderingAgentsIDHandlerFunc turns a function with the right signature into a get ordering agents ID handler
type GetOrderingAgentsIDHandlerFunc func(GetOrderingAgentsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOrderingAgentsIDHandlerFunc) Handle(params GetOrderingAgentsIDParams) middleware.Responder {
	return fn(params)
}

// GetOrderingAgentsIDHandler interface for that can handle valid get ordering agents ID params
type GetOrderingAgentsIDHandler interface {
	Handle(GetOrderingAgentsIDParams) middleware.Responder
}

// NewGetOrderingAgentsID creates a new http.Handler for the get ordering agents ID operation
func NewGetOrderingAgentsID(ctx *middleware.Context, handler GetOrderingAgentsIDHandler) *GetOrderingAgentsID {
	return &GetOrderingAgentsID{Context: ctx, Handler: handler}
}

/*
	GetOrderingAgentsID swagger:route GET /ordering-agents/{id} getOrderingAgentsId

# Get Ordering Agent View

Retrieve the view of an ordering agent.
*/
type GetOrderingAgentsID struct {
	Context *middleware.Context
	Handler GetOrderingAgentsIDHandler
}

func (o *GetOrderingAgentsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetOrderingAgentsIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
