// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"emulation/models"
)

// GetOrderingAgentViewOKCode is the HTTP code returned for type GetOrderingAgentViewOK
const GetOrderingAgentViewOKCode int = 200

/*
GetOrderingAgentViewOK Successful response

swagger:response getOrderingAgentViewOK
*/
type GetOrderingAgentViewOK struct {

	/*
	  In: Body
	*/
	Payload *models.OrderingAgentView `json:"body,omitempty"`
}

// NewGetOrderingAgentViewOK creates GetOrderingAgentViewOK with default headers values
func NewGetOrderingAgentViewOK() *GetOrderingAgentViewOK {

	return &GetOrderingAgentViewOK{}
}

// WithPayload adds the payload to the get ordering agent view o k response
func (o *GetOrderingAgentViewOK) WithPayload(payload *models.OrderingAgentView) *GetOrderingAgentViewOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get ordering agent view o k response
func (o *GetOrderingAgentViewOK) SetPayload(payload *models.OrderingAgentView) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrderingAgentViewOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
