// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"emulation/models"
)

// GetProducingAgentViewOKCode is the HTTP code returned for type GetProducingAgentViewOK
const GetProducingAgentViewOKCode int = 200

/*
GetProducingAgentViewOK Successful response

swagger:response getProducingAgentViewOK
*/
type GetProducingAgentViewOK struct {

	/*
	  In: Body
	*/
	Payload *models.ProducingAgentView `json:"body,omitempty"`
}

// NewGetProducingAgentViewOK creates GetProducingAgentViewOK with default headers values
func NewGetProducingAgentViewOK() *GetProducingAgentViewOK {

	return &GetProducingAgentViewOK{}
}

// WithPayload adds the payload to the get producing agent view o k response
func (o *GetProducingAgentViewOK) WithPayload(payload *models.ProducingAgentView) *GetProducingAgentViewOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get producing agent view o k response
func (o *GetProducingAgentViewOK) SetPayload(payload *models.ProducingAgentView) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProducingAgentViewOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
