// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetProducingAgentsIDHandlerFunc turns a function with the right signature into a get producing agents ID handler
type GetProducingAgentsIDHandlerFunc func(GetProducingAgentsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProducingAgentsIDHandlerFunc) Handle(params GetProducingAgentsIDParams) middleware.Responder {
	return fn(params)
}

// GetProducingAgentsIDHandler interface for that can handle valid get producing agents ID params
type GetProducingAgentsIDHandler interface {
	Handle(GetProducingAgentsIDParams) middleware.Responder
}

// NewGetProducingAgentsID creates a new http.Handler for the get producing agents ID operation
func NewGetProducingAgentsID(ctx *middleware.Context, handler GetProducingAgentsIDHandler) *GetProducingAgentsID {
	return &GetProducingAgentsID{Context: ctx, Handler: handler}
}

/*
	GetProducingAgentsID swagger:route GET /producing-agents/{id} getProducingAgentsId

# Get Producing Agent View

Retrieve the view of a producing agent.
*/
type GetProducingAgentsID struct {
	Context *middleware.Context
	Handler GetProducingAgentsIDHandler
}

func (o *GetProducingAgentsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetProducingAgentsIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
