// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetProducingAgentViewHandlerFunc turns a function with the right signature into a get producing agent view handler
type GetProducingAgentViewHandlerFunc func(GetProducingAgentViewParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProducingAgentViewHandlerFunc) Handle(params GetProducingAgentViewParams) middleware.Responder {
	return fn(params)
}

// GetProducingAgentViewHandler interface for that can handle valid get producing agent view params
type GetProducingAgentViewHandler interface {
	Handle(GetProducingAgentViewParams) middleware.Responder
}

// NewGetProducingAgentView creates a new http.Handler for the get producing agent view operation
func NewGetProducingAgentView(ctx *middleware.Context, handler GetProducingAgentViewHandler) *GetProducingAgentView {
	return &GetProducingAgentView{Context: ctx, Handler: handler}
}

/*
	GetProducingAgentView swagger:route GET /producing-agents/{id} getProducingAgentView

# Get Producing Agent View

Retrieve the view of a producing agent.
*/
type GetProducingAgentView struct {
	Context *middleware.Context
	Handler GetProducingAgentViewHandler
}

func (o *GetProducingAgentView) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetProducingAgentViewParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
