// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListOrderingAgentsHandlerFunc turns a function with the right signature into a list ordering agents handler
type ListOrderingAgentsHandlerFunc func(ListOrderingAgentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListOrderingAgentsHandlerFunc) Handle(params ListOrderingAgentsParams) middleware.Responder {
	return fn(params)
}

// ListOrderingAgentsHandler interface for that can handle valid list ordering agents params
type ListOrderingAgentsHandler interface {
	Handle(ListOrderingAgentsParams) middleware.Responder
}

// NewListOrderingAgents creates a new http.Handler for the list ordering agents operation
func NewListOrderingAgents(ctx *middleware.Context, handler ListOrderingAgentsHandler) *ListOrderingAgents {
	return &ListOrderingAgents{Context: ctx, Handler: handler}
}

/*
	ListOrderingAgents swagger:route GET /ordering-agents listOrderingAgents

Get ordering agents list
*/
type ListOrderingAgents struct {
	Context *middleware.Context
	Handler ListOrderingAgentsHandler
}

func (o *ListOrderingAgents) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListOrderingAgentsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
