// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"emulation/models"
)

// ListOrderingAgentsOKCode is the HTTP code returned for type ListOrderingAgentsOK
const ListOrderingAgentsOKCode int = 200

/*
ListOrderingAgentsOK OK

swagger:response listOrderingAgentsOK
*/
type ListOrderingAgentsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.OrderingAgentInfo `json:"body,omitempty"`
}

// NewListOrderingAgentsOK creates ListOrderingAgentsOK with default headers values
func NewListOrderingAgentsOK() *ListOrderingAgentsOK {

	return &ListOrderingAgentsOK{}
}

// WithPayload adds the payload to the list ordering agents o k response
func (o *ListOrderingAgentsOK) WithPayload(payload []*models.OrderingAgentInfo) *ListOrderingAgentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list ordering agents o k response
func (o *ListOrderingAgentsOK) SetPayload(payload []*models.OrderingAgentInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListOrderingAgentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.OrderingAgentInfo, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
