// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListProducingAgentsHandlerFunc turns a function with the right signature into a list producing agents handler
type ListProducingAgentsHandlerFunc func(ListProducingAgentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListProducingAgentsHandlerFunc) Handle(params ListProducingAgentsParams) middleware.Responder {
	return fn(params)
}

// ListProducingAgentsHandler interface for that can handle valid list producing agents params
type ListProducingAgentsHandler interface {
	Handle(ListProducingAgentsParams) middleware.Responder
}

// NewListProducingAgents creates a new http.Handler for the list producing agents operation
func NewListProducingAgents(ctx *middleware.Context, handler ListProducingAgentsHandler) *ListProducingAgents {
	return &ListProducingAgents{Context: ctx, Handler: handler}
}

/*
	ListProducingAgents swagger:route GET /producer-agents listProducingAgents

Get producing agents list
*/
type ListProducingAgents struct {
	Context *middleware.Context
	Handler ListProducingAgentsHandler
}

func (o *ListProducingAgents) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListProducingAgentsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
