// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostProducingAgentsIDOKCode is the HTTP code returned for type PostProducingAgentsIDOK
const PostProducingAgentsIDOKCode int = 200

/*
PostProducingAgentsIDOK Command processed successfully

swagger:response postProducingAgentsIdOK
*/
type PostProducingAgentsIDOK struct {
}

// NewPostProducingAgentsIDOK creates PostProducingAgentsIDOK with default headers values
func NewPostProducingAgentsIDOK() *PostProducingAgentsIDOK {

	return &PostProducingAgentsIDOK{}
}

// WriteResponse to the client
func (o *PostProducingAgentsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
