// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostOrderingAgentsIDOKCode is the HTTP code returned for type PostOrderingAgentsIDOK
const PostOrderingAgentsIDOKCode int = 200

/*
PostOrderingAgentsIDOK Command processed successfully

swagger:response postOrderingAgentsIdOK
*/
type PostOrderingAgentsIDOK struct {
}

// NewPostOrderingAgentsIDOK creates PostOrderingAgentsIDOK with default headers values
func NewPostOrderingAgentsIDOK() *PostOrderingAgentsIDOK {

	return &PostOrderingAgentsIDOK{}
}

// WriteResponse to the client
func (o *PostOrderingAgentsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
