// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostOrderingAgentsIDHandlerFunc turns a function with the right signature into a post ordering agents ID handler
type PostOrderingAgentsIDHandlerFunc func(PostOrderingAgentsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostOrderingAgentsIDHandlerFunc) Handle(params PostOrderingAgentsIDParams) middleware.Responder {
	return fn(params)
}

// PostOrderingAgentsIDHandler interface for that can handle valid post ordering agents ID params
type PostOrderingAgentsIDHandler interface {
	Handle(PostOrderingAgentsIDParams) middleware.Responder
}

// NewPostOrderingAgentsID creates a new http.Handler for the post ordering agents ID operation
func NewPostOrderingAgentsID(ctx *middleware.Context, handler PostOrderingAgentsIDHandler) *PostOrderingAgentsID {
	return &PostOrderingAgentsID{Context: ctx, Handler: handler}
}

/*
	PostOrderingAgentsID swagger:route POST /ordering-agents/{id} postOrderingAgentsId

# Submit Ordering Agent Command

Send a command to an ordering agent.
*/
type PostOrderingAgentsID struct {
	Context *middleware.Context
	Handler PostOrderingAgentsIDHandler
}

func (o *PostOrderingAgentsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostOrderingAgentsIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
