// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SendProducingAgentCommandOKCode is the HTTP code returned for type SendProducingAgentCommandOK
const SendProducingAgentCommandOKCode int = 200

/*
SendProducingAgentCommandOK Command processed successfully

swagger:response sendProducingAgentCommandOK
*/
type SendProducingAgentCommandOK struct {
}

// NewSendProducingAgentCommandOK creates SendProducingAgentCommandOK with default headers values
func NewSendProducingAgentCommandOK() *SendProducingAgentCommandOK {

	return &SendProducingAgentCommandOK{}
}

// WriteResponse to the client
func (o *SendProducingAgentCommandOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
