// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SendOrderingAgentCommandOKCode is the HTTP code returned for type SendOrderingAgentCommandOK
const SendOrderingAgentCommandOKCode int = 200

/*
SendOrderingAgentCommandOK Command processed successfully

swagger:response sendOrderingAgentCommandOK
*/
type SendOrderingAgentCommandOK struct {
}

// NewSendOrderingAgentCommandOK creates SendOrderingAgentCommandOK with default headers values
func NewSendOrderingAgentCommandOK() *SendOrderingAgentCommandOK {

	return &SendOrderingAgentCommandOK{}
}

// WriteResponse to the client
func (o *SendOrderingAgentCommandOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
