// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateConfigOKCode is the HTTP code returned for type UpdateConfigOK
const UpdateConfigOKCode int = 200

/*
UpdateConfigOK Configuration updated successfully

swagger:response updateConfigOK
*/
type UpdateConfigOK struct {
}

// NewUpdateConfigOK creates UpdateConfigOK with default headers values
func NewUpdateConfigOK() *UpdateConfigOK {

	return &UpdateConfigOK{}
}

// WriteResponse to the client
func (o *UpdateConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateConfigBadRequestCode is the HTTP code returned for type UpdateConfigBadRequest
const UpdateConfigBadRequestCode int = 400

/*
UpdateConfigBadRequest Invalid configuration

swagger:response updateConfigBadRequest
*/
type UpdateConfigBadRequest struct {
}

// NewUpdateConfigBadRequest creates UpdateConfigBadRequest with default headers values
func NewUpdateConfigBadRequest() *UpdateConfigBadRequest {

	return &UpdateConfigBadRequest{}
}

// WriteResponse to the client
func (o *UpdateConfigBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
