swagger: "2.0"
info:
  version: "1.0.0"
  title: tokenomics

host: "localhost:9090"
basePath: "/"
schemes:
  - "http"
produces:
  - application/json
consumes:
  - application/json
paths:
  /system:
    get:
      operationId: getSystemInfo
      summary: Get system state
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/SystemInfo"
    delete:
      operationId: resetSystem
      tags:
        - Tokenomics
      summary: "Reset emulation state"
      responses:
        200:
          description: OK
  /system/complete-investment:
    post:
      operationId: completeInvestment
      summary: Complete investment phase
      tags:
        - Tokenomics
      responses:
        200:
          description: OK
  /system/complete-cycle:
    post:
      operationId: completeCycle
      summary: Complete current cycle
      tags:
        - Tokenomics
      responses:
        200:
          description: OK

  /producer-agents:
    get:
      operationId: listProducingAgents
      summary: Get producing agents list
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/ProducingAgentInfo"
  /ordering-agents:
    get:
      operationId: listOrderingAgents
      summary: Get producer agens list
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/ProducingAgentInfo"

  /ordering-agents/{id}:
    parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
    get:
      operationId: getOrderingAgentView
      summary: "Get Ordering Agent View"
      description: "Retrieve the view of an ordering agent."
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/OrderingAgentView"
    post:
      operationId: sendOrderingAgentCommand
      summary: "Submit Ordering Agent Command"
      description: "Send a command to an ordering agent."
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/OrderingAgentCommand"
      responses:
        200:
          description: "Command processed successfully"

  /producing-agents/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: string
    get:
      operationId: getProducingAgentView
      summary: "Get Producing Agent View"
      description: "Retrieve the view of a producing agent."
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/ProducingAgentView"
    post:
      operationId: sendProducingAgentCommand
      summary: "Submit Producing Agent Command"
      description: "Send a command to a producing agent."
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/ProducingAgentCommand"
      responses:
        200:
          description: "Command processed successfully"
definitions:
  OrderingAgentView:
    description: Ordering agent view
    example:
      incoming:
        order-1:
          capacity-1: 110
          capacity-2: 350
        order-2:
          capacity-3: 55
      producers:
        capacity-1:
          producer-1:
            id: "producer-1"
            maxCapacity: 150
            capacity: 120
            requestedCapacity: 500
            degradation: 5
            upgrade: 10
            restoration: 20
            upgradeRunning: "true"
            restorationRunning: "false"
    type: "object"
    properties:
      Incoming:
        type: "object"
        additionalProperties:
          type: "object"
          additionalProperties:
            type: "integer"
      Producers:
        type: "object"
        additionalProperties:
          type: "object"
          additionalProperties:
            $ref: "#/definitions/ProducingAgentInfo"

  OrderingAgentCommand:
    example:
      orders:
        order-1:
          producer-1: 110
          producer-2: 350
        order-2:
          producer-2: 10
          producer-3: 50
    description: Ordering agent command
    type: "object"
    properties:
      Orders:
        type: "object"
        additionalProperties:
          type: "object"
          additionalProperties:
            type: "integer"

  ProducingAgentView:
    type: "object"
    properties:
      Id:
        description: Agent ID
        type: "string"
      MaxCapacity:
        description: Maximum capacity. Can be increased with Upgrade purchase
        type: "integer"
      Capacity:
        description: Current capacity. Degradates each turn. Could be increased to MaxCapacity with Restoration purchase
        type: "integer"
      RequestedCapacity:
        description: Total capacity was requested in the previous cycle
        type: "integer"
      Degradation:
        description: Capacity decrease in the current cycle
        type: "integer"
      Upgrade:
        description: MaxCapacity and Capacity gain with Upgrade
        type: "integer"
      Restoration:
        description: Capacity gain with Restoration
        type: "integer"
      UpgradeRunning:
        description: Indicates Upgrade production is running
        type: "boolean"
      RestorationRunning:
        description: Indicates Restoration production is running
        type: "boolean"

  ProducingAgentCommand:
    type: "object"
    properties:
      DoRestoration:
        description: Pass true for purchasing of Restoration (Not allowed if Restoration is producing)
        type: "boolean"
      DoUpgrade:
        description: Pass true for purchasing of Upgrade (Not allowed if Upgrade is producing)
        type: "boolean"

  ProducingAgentInfo:
    type: "object"
    properties:
      Id:
        description: Agent ID
        type: "string"
      CapacityType:
        description: Capacity type
        type: "integer"
      Capacity:
        description: Current capacity value
        type: "integer"
      MaxCapacity:
        description: Maximum capacity value
        type: "integer"
      CutOffPrice:
        description: The cut off price in the previous cycle
        type: "integer"

  OrderingAgentInfo:
    type: "object"
    properties:
      Id:
        description: Agent ID
        type: "string"

  SystemInfo:
    type: "object"
    properties:
      CycleCounter:
        type: "integer"
      State:
        type: string
        enum:
          - OrdersPlacement
          - Ordering
