// Code generated by go-swagger; DO NOT EDIT.

package tokenomics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CompleteCycleHandlerFunc turns a function with the right signature into a complete cycle handler
type CompleteCycleHandlerFunc func(CompleteCycleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CompleteCycleHandlerFunc) Handle(params CompleteCycleParams) middleware.Responder {
	return fn(params)
}

// CompleteCycleHandler interface for that can handle valid complete cycle params
type CompleteCycleHandler interface {
	Handle(CompleteCycleParams) middleware.Responder
}

// NewCompleteCycle creates a new http.Handler for the complete cycle operation
func NewCompleteCycle(ctx *middleware.Context, handler CompleteCycleHandler) *CompleteCycle {
	return &CompleteCycle{Context: ctx, Handler: handler}
}

/*
	CompleteCycle swagger:route POST /system/complete-cycle Tokenomics completeCycle

Complete current cycle
*/
type CompleteCycle struct {
	Context *middleware.Context
	Handler CompleteCycleHandler
}

func (o *CompleteCycle) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCompleteCycleParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
