// Code generated by go-swagger; DO NOT EDIT.

package tokenomics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ResetSystemOKCode is the HTTP code returned for type ResetSystemOK
const ResetSystemOKCode int = 200

/*
ResetSystemOK OK

swagger:response resetSystemOK
*/
type ResetSystemOK struct {
}

// NewResetSystemOK creates ResetSystemOK with default headers values
func NewResetSystemOK() *ResetSystemOK {

	return &ResetSystemOK{}
}

// WriteResponse to the client
func (o *ResetSystemOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
