// Code generated by go-swagger; DO NOT EDIT.

package tokenomics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ResetSystemHandlerFunc turns a function with the right signature into a reset system handler
type ResetSystemHandlerFunc func(ResetSystemParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ResetSystemHandlerFunc) Handle(params ResetSystemParams) middleware.Responder {
	return fn(params)
}

// ResetSystemHandler interface for that can handle valid reset system params
type ResetSystemHandler interface {
	Handle(ResetSystemParams) middleware.Responder
}

// NewResetSystem creates a new http.Handler for the reset system operation
func NewResetSystem(ctx *middleware.Context, handler ResetSystemHandler) *ResetSystem {
	return &ResetSystem{Context: ctx, Handler: handler}
}

/*
	ResetSystem swagger:route DELETE /system Tokenomics resetSystem

Reset emulation state
*/
type ResetSystem struct {
	Context *middleware.Context
	Handler ResetSystemHandler
}

func (o *ResetSystem) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewResetSystemParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
