// Code generated by go-swagger; DO NOT EDIT.

package tokenomics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// StartOrderingOKCode is the HTTP code returned for type StartOrderingOK
const StartOrderingOKCode int = 200

/*
StartOrderingOK OK

swagger:response startOrderingOK
*/
type StartOrderingOK struct {
}

// NewStartOrderingOK creates StartOrderingOK with default headers values
func NewStartOrderingOK() *StartOrderingOK {

	return &StartOrderingOK{}
}

// WriteResponse to the client
func (o *StartOrderingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
