// Code generated by go-swagger; DO NOT EDIT.

package tokenomics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// StartOrderingHandlerFunc turns a function with the right signature into a start ordering handler
type StartOrderingHandlerFunc func(StartOrderingParams) middleware.Responder

// Handle executing the request and returning a response
func (fn StartOrderingHandlerFunc) Handle(params StartOrderingParams) middleware.Responder {
	return fn(params)
}

// StartOrderingHandler interface for that can handle valid start ordering params
type StartOrderingHandler interface {
	Handle(StartOrderingParams) middleware.Responder
}

// NewStartOrdering creates a new http.Handler for the start ordering operation
func NewStartOrdering(ctx *middleware.Context, handler StartOrderingHandler) *StartOrdering {
	return &StartOrdering{Context: ctx, Handler: handler}
}

/*
	StartOrdering swagger:route POST /system/start-ordering Tokenomics startOrdering

Complete investment phase
*/
type StartOrdering struct {
	Context *middleware.Context
	Handler StartOrderingHandler
}

func (o *StartOrdering) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewStartOrderingParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
