// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Configuration configuration
//
// swagger:model Configuration
type Configuration struct {

	// Amount of tokens emitted each cycle
	// Required: true
	CycleEmission *int64 `json:"cycleEmission"`

	// process sheets
	// Required: true
	ProcessSheets []*ProcessSheet `json:"processSheets"`

	// producer configs
	// Required: true
	ProducerConfigs []*ProducingAgentConfig `json:"producerConfigs"`
}

// Validate validates this configuration
func (m *Configuration) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCycleEmission(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProcessSheets(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProducerConfigs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Configuration) validateCycleEmission(formats strfmt.Registry) error {

	if err := validate.Required("cycleEmission", "body", m.CycleEmission); err != nil {
		return err
	}

	return nil
}

func (m *Configuration) validateProcessSheets(formats strfmt.Registry) error {

	if err := validate.Required("processSheets", "body", m.ProcessSheets); err != nil {
		return err
	}

	for i := 0; i < len(m.ProcessSheets); i++ {
		if swag.IsZero(m.ProcessSheets[i]) { // not required
			continue
		}

		if m.ProcessSheets[i] != nil {
			if err := m.ProcessSheets[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("processSheets" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("processSheets" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Configuration) validateProducerConfigs(formats strfmt.Registry) error {

	if err := validate.Required("producerConfigs", "body", m.ProducerConfigs); err != nil {
		return err
	}

	for i := 0; i < len(m.ProducerConfigs); i++ {
		if swag.IsZero(m.ProducerConfigs[i]) { // not required
			continue
		}

		if m.ProducerConfigs[i] != nil {
			if err := m.ProducerConfigs[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("producerConfigs" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("producerConfigs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this configuration based on the context it is used
func (m *Configuration) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateProcessSheets(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProducerConfigs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Configuration) contextValidateProcessSheets(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ProcessSheets); i++ {

		if m.ProcessSheets[i] != nil {

			if swag.IsZero(m.ProcessSheets[i]) { // not required
				return nil
			}

			if err := m.ProcessSheets[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("processSheets" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("processSheets" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Configuration) contextValidateProducerConfigs(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ProducerConfigs); i++ {

		if m.ProducerConfigs[i] != nil {

			if swag.IsZero(m.ProducerConfigs[i]) { // not required
				return nil
			}

			if err := m.ProducerConfigs[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("producerConfigs" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("producerConfigs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Configuration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Configuration) UnmarshalBinary(b []byte) error {
	var res Configuration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
