// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrderingAgentInfo ordering agent info
//
// swagger:model OrderingAgentInfo
type OrderingAgentInfo struct {

	// Agent ID
	ID string `json:"id,omitempty"`
}

// Validate validates this ordering agent info
func (m *OrderingAgentInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ordering agent info based on context it is used
func (m *OrderingAgentInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderingAgentInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderingAgentInfo) UnmarshalBinary(b []byte) error {
	var res OrderingAgentInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
