// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrderingAgentCommand Ordering agent command
// Example: {"orders":{"order-1":{"producer-1":110,"producer-2":350},"order-2":{"producer-2":10,"producer-3":50}}}
//
// swagger:model OrderingAgentCommand
type OrderingAgentCommand struct {

	// orders
	Orders map[string]map[string]int64 `json:"Orders,omitempty"`
}

// Validate validates this ordering agent command
func (m *OrderingAgentCommand) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ordering agent command based on context it is used
func (m *OrderingAgentCommand) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderingAgentCommand) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderingAgentCommand) UnmarshalBinary(b []byte) error {
	var res OrderingAgentCommand
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
