// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProcessSheet process sheet
//
// swagger:model ProcessSheet
type ProcessSheet struct {

	// Product identifier
	// Required: true
	Product *int64 `json:"product"`

	// Map of capacity type to required capacity
	// Required: true
	Require map[string]int64 `json:"require"`
}

// Validate validates this process sheet
func (m *ProcessSheet) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProduct(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequire(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProcessSheet) validateProduct(formats strfmt.Registry) error {

	if err := validate.Required("product", "body", m.Product); err != nil {
		return err
	}

	return nil
}

func (m *ProcessSheet) validateRequire(formats strfmt.Registry) error {

	if err := validate.Required("require", "body", m.Require); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this process sheet based on context it is used
func (m *ProcessSheet) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProcessSheet) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProcessSheet) UnmarshalBinary(b []byte) error {
	var res ProcessSheet
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
