// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProducingAgentCommand producing agent command
//
// swagger:model ProducingAgentCommand
type ProducingAgentCommand struct {

	// Pass true for purchasing of Restoration (Not allowed if Restoration is producing)
	DoRestoration bool `json:"DoRestoration,omitempty"`

	// Pass true for purchasing of Upgrade (Not allowed if Upgrade is producing)
	DoUpgrade bool `json:"DoUpgrade,omitempty"`
}

// Validate validates this producing agent command
func (m *ProducingAgentCommand) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this producing agent command based on context it is used
func (m *ProducingAgentCommand) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProducingAgentCommand) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProducingAgentCommand) UnmarshalBinary(b []byte) error {
	var res ProducingAgentCommand
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
