// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SystemInfo system info
//
// swagger:model SystemInfo
type SystemInfo struct {

	// cycle counter
	CycleCounter int64 `json:"cycleCounter,omitempty"`

	// state
	// Enum: ["OrdersPlacement","Ordering"]
	State string `json:"state,omitempty"`
}

// Validate validates this system info
func (m *SystemInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var systemInfoTypeStatePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["OrdersPlacement","Ordering"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		systemInfoTypeStatePropEnum = append(systemInfoTypeStatePropEnum, v)
	}
}

const (

	// SystemInfoStateOrdersPlacement captures enum value "OrdersPlacement"
	SystemInfoStateOrdersPlacement string = "OrdersPlacement"

	// SystemInfoStateOrdering captures enum value "Ordering"
	SystemInfoStateOrdering string = "Ordering"
)

// prop value enum
func (m *SystemInfo) validateStateEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, systemInfoTypeStatePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *SystemInfo) validateState(formats strfmt.Registry) error {
	if swag.IsZero(m.State) { // not required
		return nil
	}

	// value enum
	if err := m.validateStateEnum("state", "body", m.State); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this system info based on context it is used
func (m *SystemInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SystemInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SystemInfo) UnmarshalBinary(b []byte) error {
	var res SystemInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
