// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Upgrade upgrade
//
// swagger:model Upgrade
type Upgrade struct {

	// Capacity increase after upgrade
	Capacity int64 `json:"capacity,omitempty"`

	// Product required for upgrade
	Product int64 `json:"product,omitempty"`
}

// Validate validates this upgrade
func (m *Upgrade) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this upgrade based on context it is used
func (m *Upgrade) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Upgrade) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Upgrade) UnmarshalBinary(b []byte) error {
	var res Upgrade
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
